# Generated by Django 5.1.1 on 2024-10-06 06:56

import api.models
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('long_url', models.URLField(max_length=4000, unique=True)),
                ('short_url', models.URLField(max_length=20, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[api.models.validate_code_length])),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
