# Generated by Django 5.1.1 on 2024-10-06 07:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_shorten_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorten',
            name='short_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[api.models.validate_code_length]),
        ),
    ]
